// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsConstants {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-UkGLXZ8neuuKXMhrs3khIwAJUr_8XU',
    appId: '1:707744483232:web:ce57c18d7dbb7af10ac6c5',
    messagingSenderId: '707744483232',
    projectId: 'realtime-demo-a5562',
    authDomain: 'realtime-demo-a5562.firebaseapp.com',
    databaseURL: 'https://realtime-demo-a5562-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-demo-a5562.appspot.com',
    measurementId: 'G-Y99SGGDW8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5wymMkthoFmaUrbxadeyCSwA-b6Qa4EM',
    appId: '1:707744483232:android:23d520554c4164910ac6c5',
    messagingSenderId: '707744483232',
    projectId: 'realtime-demo-a5562',
    databaseURL: 'https://realtime-demo-a5562-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-demo-a5562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa8lDyPv9mYDRya9r6LL-3kiLrn_oFLP0',
    appId: '1:707744483232:ios:8d98d90ff336c94a0ac6c5',
    messagingSenderId: '707744483232',
    projectId: 'realtime-demo-a5562',
    databaseURL: 'https://realtime-demo-a5562-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-demo-a5562.appspot.com',
    androidClientId: '707744483232-144t188ftq41hftsuf272kuemh69gcsa.apps.googleusercontent.com',
    iosClientId: '707744483232-9o6l5tp0rkg8i54b647epqq9n9om43pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeDatabaseApp',
  );
}
